### ISSUE TITLE
Unable to send invite people to slack, programatically.

### ISSUE THREAD

**Issue by balaprasanna** [avinassh/slackipycore#1]
I am using your core module, directly
invite(team_id="myteam", api_token=slack_token, invitee_email="someone@gmail.com")
ERROR:
Unable to send invite from slack api.
RESP:
{u'needed': u'client', u'provided': u'identify,bot:basic', u'ok': False, u'error': u'missing_scope'}

Please help

**Comment by avinassh** [comment]
Is the API key has all the permissions? it has to be generated from an Admin account

**Comment by balaprasanna** [comment]
yeah, your are correct. I had problem with the API key.
Thanks for your reply. It was my mistake that i was using a wrong api key.
