### ISSUE TITLE
How about removing users?

### ISSUE THREAD

**Issue by elDudarino** [avinassh/slackipycore#4]
Cool little package guys, thank you for taking the time.

Seems really handy for a project I am working on, however inviting users to the workspace and channel are only 1/2 the battle, I need to be able to entirely remove them from the workspace as well. 

Any ideas? Thanks again!

**Comment by avinassh** [comment]
Hey, you can use this API - https://api.slack.com/methods/admin.users.remove

**Comment by elDudarino** [comment]
Hey, thanks Avinassh... that's not available through the Python API though, is it? Would you have an example on how to do it via Python? Thanks for the quick reply.

**Comment by avinassh** [comment]
Yes, it's not available, so you'd have to write one. I don't have an example script
